# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Aatish
tagline:          ''
description:      ''
url:              http://aatishrana.github.io
baseurl:          
#commentsystem:    google
#disqus:           example

author:
  name:           Aatish Rana
  url:            https://aatishrana.github.io
  email:          aatishranawork@gmail.com

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  - icon:         github
    url:          https://github.com/aatishrana
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://plus.google.com/u/0/108958764638006156141
    desc:         Add me on google+

  - icon:         feed
    url:          http://aatishrana.github.io/atom.xml
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        Projects
    url:          /projects

  - title:        About
    url:          /about

copyright:
  author:         Aatish
  url:            http://aatishrana.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
